version: '3'
services:
  mongodb:
    image: mongo_db
    ports:
      - '27017:27017'

  mongo_data:
    image: mongo_db
    command: bash -c "mongoimport --host mongodb --jsonArray -d co2sim -c formations mongo_data/formations.json && mongoimport --host mongodb --jsonArray -d co2sim -c formations_data mongo_data/formations_data.json"
    links:
    - mongodb

  co2sim:
    image: app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
