version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  mongo_data:
    build: ./mongo_data
    links:
    - mongodb

  co2sim:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
